language: "perl"
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

before_install:
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest .

script: "perl Build.PL; ./Build test"

notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
